// frameworkData.js - contiene la fuente de verdad con los controles (IG1 ejemplo)
const frameworkData = {
  nistFunctions: {
    gobernar: 'Gobernar', identificar: 'Identificar', proteger: 'Proteger', detectar: 'Detectar', responder: 'Responder', recuperar: 'Recuperar'
  },
  cisControls: [
    { id: '1.1', nistFunction: 'gobernar', title: 'Política y responsabilidades', description: 'Documento básico que define responsabilidades y objetivos de seguridad.', question: '¿Existe una política o documento que defina responsabilidades y objetivos de seguridad?', guidance: { why: 'Provee dirección y responsabilidad para decisiones de seguridad.', steps: ['Nombre a una persona responsable.','Documente 3-5 políticas mínimas (acceso, backups, actualizaciones).'] } },
    { id: '1.2', nistFunction: 'gobernar', title: 'Inventario de roles y permisos', description: 'Registro de roles clave y permisos asociados.', question: '¿Sabe quién tiene acceso a qué sistemas críticos?', guidance: { why: 'Controlar permisos reduce el riesgo de accesos indebidos.', steps: ['Liste roles con sus permisos.','Revise cambios de rol al modificar personal.'] } },
    { id: '1.3', nistFunction: 'gobernar', title: 'Gestión de proveedores', description: 'Evaluación básica de seguridad de terceros.', question: '¿Evalúa la seguridad de proveedores que manejan datos o sistemas críticos?', guidance: { why: 'Los proveedores pueden introducir riesgo si no se gestionan.', steps: ['Cree una lista de proveedores críticos.','Solicite controles mínimos o un checklist de seguridad.'] } },
    { id: '1.4', nistFunction: 'gobernar', title: 'Plan mínimo de continuidad', description: 'Plan básico para mantener operaciones críticas.', question: '¿Tiene un plan básico para mantener operaciones tras un incidente (respaldo y contactos)?', guidance: { why: 'Un plan mínimo reduce tiempo de inactividad.', steps: ['Identifique servicios críticos.','Defina pasos para restaurar los más importantes.'] } },
    { id: '1.5', nistFunction: 'gobernar', title: 'Registro de activos principales', description: 'Lista de activos críticos (servidores, bases de datos).', question: '¿Conoce sus activos más críticos para la operación del negocio?', guidance: { why: 'Prioriza la protección y el mantenimiento de recursos clave.', steps: ['Liste 10 activos críticos.','Asigne propietario y frecuencia de revisión.'] } },

    { id: '2.1', nistFunction: 'identificar', title: 'Inventario de dispositivos', description: 'Registro de equipos conectados a la red.', question: '¿Mantiene un inventario de dispositivos (PC, móviles, servidores)?', guidance: { why: 'Conocer dispositivos facilita parches y respuesta a incidentes.', steps: ['Empiece por los 10 equipos más importantes.','Mantenga la lista actualizada tras altas/bajas.'] } },
    { id: '2.2', nistFunction: 'identificar', title: 'Clasificación de datos', description: 'Clasificar datos por sensibilidad.', question: '¿Clasifica sus datos según sensibilidad o impacto en el negocio?', guidance: { why: 'Ayuda a aplicar controles apropiados a la información sensible.', steps: ['Defina categorías (público, interno, sensible).','Documente qué datos pertenecen a cada categoría.'] } },
    { id: '2.3', nistFunction: 'identificar', title: 'Inventario de software', description: 'Registro de aplicaciones críticas en uso.', question: '¿Tiene un inventario de las aplicaciones y servicios que usa la empresa?', guidance: { why: 'Permite mantener actualizaciones y retirar software inseguro.', steps: ['Liste aplicaciones en servidores y PC clave.','Revise licencias y versiones.'] } },
    { id: '2.4', nistFunction: 'identificar', title: 'Mapeo de dependencias', description: 'Identificar dependencias entre servicios.', question: '¿Conoce qué sistemas dependen de otros para funcionar?', guidance: { why: 'Ayuda a priorizar recuperación y mitigaciones.', steps: ['Identifique dependencias críticas.','Documente el orden de restauración.'] } },
    { id: '2.5', nistFunction: 'identificar', title: 'Visibilidad básica de red', description: 'Capacidad para ver dispositivos y tráfico esencial.', question: '¿Puede ver qué dispositivos se conectan a su red y tráfico básico?', guidance: { why: 'Visibilidad permite detectar actividad sospechosa.', steps: ['Revise logs del router y firewall.','Segmente red cuando sea posible.'] } },

    { id: '3.1', nistFunction: 'proteger', title: 'Configuración segura por defecto', description: 'Usar configuraciones seguras en equipos nuevos.', question: '¿Aplica configuraciones seguras al desplegar equipos nuevos?', guidance: { why: 'Reduce vectores comunes de ataque en equipos recién instalados.', steps: ['Cree una checklist de configuración inicial.','Automatice pasos repetitivos cuando sea posible.'] } },
    { id: '3.2', nistFunction: 'proteger', title: 'Gestión de cuentas y accesos', description: 'Procedimientos para crear y eliminar cuentas.', question: '¿Existe un proceso para crear, revisar y eliminar cuentas de usuario?', guidance: { why: 'Cuentas innecesarias aumentan riesgo de accesos no autorizados.', steps: ['Revise cuentas inactivas mensualmente.','Elimine o desactive cuentas cuando un empleado sale.'] } },
    { id: '3.3', nistFunction: 'proteger', title: 'Principio de menor privilegio', description: 'Asignar permisos mínimos necesarios.', question: '¿Los usuarios tienen solo los permisos que necesitan?', guidance: { why: 'Limita el impacto de accesos comprometidos.', steps: ['Revise permisos en herramientas críticas.','Use roles en lugar de permisos directos cuando sea posible.'] } },
    { id: '3.4', nistFunction: 'proteger', title: 'Política de contraseñas', description: 'Reglas mínimas para contraseñas y gestión.', question: '¿Dispone de reglas mínimas para la creación y almacenamiento de contraseñas?', guidance: { why: 'Contraseñas débiles son vectores comunes de intrusión.', steps: ['Exija contraseñas únicas y complejas.','Promueva gestores de contraseñas.'] } },
    { id: '3.5', nistFunction: 'proteger', title: 'Eliminar datos de forma segura', description: 'Borrado seguro de soportes retirados.', question: '¿Borra o destruye de forma segura los soportes antes de descartarlos?', guidance: { why: 'Previene fuga de información desde dispositivos retirados.', steps: ['Use herramientas de borrado seguro.','Registre la eliminación física cuando corresponda.'] } },
    { id: '3.6', nistFunction: 'proteger', title: 'Cifrado de dispositivos', description: 'Cifrado de discos en portátiles y móviles.', question: '¿Los dispositivos móviles y portátiles tienen cifrado de disco habilitado?', guidance: { why: 'Protege datos en caso de pérdida o robo.', steps: ['Active BitLocker/FileVault donde aplique.','Gestione claves de recuperación de forma segura.'] } },

    { id: '4.1', nistFunction: 'detectar', title: 'Registro de eventos básicos', description: 'Habilitar registros esenciales (inicio de sesión, cambios de cuenta).', question: '¿Genera registros básicos que permitan investigar incidentes?', guidance: { why: 'Los registros son la base de cualquier investigación forense.', steps: ['Active logs en servicios críticos.','Conserve registros mínimamente por 30 días.'] } },
    { id: '4.2', nistFunction: 'detectar', title: 'Monitoreo de alertas', description: 'Revisión periódica de alertas simples.', question: '¿Alguien revisa regularmente logs o alertas críticas?', guidance: { why: 'La detección temprana reduce el impacto de incidentes.', steps: ['Determine quién revisa y con qué frecuencia.','Priorice alertas de accesos fallidos y cambios de cuentas.'] } },
    { id: '4.3', nistFunction: 'detectar', title: 'Detección de software no autorizado', description: 'Procesos para identificar software desconocido.', question: '¿Tiene forma de detectar software no autorizado en equipos clave?', guidance: { why: 'Software no autorizado puede contener amenazas.', steps: ['Compare inventario de software con listas permitidas.','Establezca proceso para eliminar aplicaciones no aprobadas.'] } },
    { id: '4.4', nistFunction: 'detectar', title: 'Análisis de incidentes básicos', description: 'Capacidad para analizar incidentes simples.', question: '¿Sabe cómo analizar un incidente de seguridad básico (e.g., PC infectado)?', guidance: { why: 'Permite responder adecuadamente y restaurar operaciones.', steps: ['Documente pasos de contención básicos.','Determinar cuándo escalar a experto externo.'] } },
    { id: '4.5', nistFunction: 'detectar', title: 'Medición y seguimiento', description: 'Métricas simples para medir efectividad de controles.', question: '¿Mide algún indicador de seguridad (incidentes, parches pendientes)?', guidance: { why: 'Medir permite mejorar con el tiempo.', steps: ['Defina 2-3 métricas clave.','Revise métricas trimestralmente.'] } },

    { id: '5.1', nistFunction: 'responder', title: 'Plan de respuesta básico', description: 'Procedimiento simple para responder incidentes.', question: '¿Tiene pasos documentados para responder a incidentes de seguridad básicos?', guidance: { why: 'Un plan corto acelera la contención inicial.', steps: ['Defina responsables y contactos.','Documente acciones inmediatas (aislar equipo, cambiar contraseñas).'] } },
    { id: '5.2', nistFunction: 'responder', title: 'Política de contraseñas únicas', description: 'Evitar reutilización y compartir contraseñas.', question: '¿Existen reglas que impidan compartir o reutilizar contraseñas?', guidance: { why: 'La reutilización amplifica el impacto de una filtración.', steps: ['Prohibir compartir contraseñas por escrito.','Promover MFA para cuentas críticas.'] } },
    { id: '5.3', nistFunction: 'responder', title: 'Contactos y escalamiento', description: 'Lista de contactos clave para incidentes.', question: '¿Mantiene una lista de contactos para responder a incidentes (internos y externos)?', guidance: { why: 'La comunicación rápida mejora la respuesta.', steps: ['Cree y distribuya la lista de contactos.','Incluya proveedores y soporte técnico.'] } },
    { id: '5.4', nistFunction: 'responder', title: 'Comunicación en incidentes', description: 'Mensajes y canales para comunicar incidentes.', question: '¿Tiene definidos canales y mensajes básicos para comunicar un incidente?', guidance: { why: 'La comunicación controlada reduce daño reputacional.', steps: ['Predefina mensajes para clientes y empleados.','Decida quién autoriza las comunicaciones.'] } },
    { id: '5.5', nistFunction: 'responder', title: 'Registro de incidentes', description: 'Documentar incidentes y aprendizaje.', question: '¿Registra los incidentes y las lecciones aprendidas?', guidance: { why: 'Aprender reduce probabilidad de repetición.', steps: ['Mantenga un registro simple con fecha, impacto y acciones.','Realice una revisión post-incidente.'] } },

    { id: '6.1', nistFunction: 'recuperar', title: 'Backups mínimos', description: 'Política de copias para datos críticos.', question: '¿Se realizan copias de seguridad para datos críticos?', guidance: { why: 'Permite recuperación ante pérdida o ransomware.', steps: ['Defina qué datos son críticos.','Asegure backups automáticos y copias fuera del sitio.'] } },
    { id: '6.2', nistFunction: 'recuperar', title: 'Pruebas de restauración', description: 'Verificar que los backups se puedan restaurar.', question: '¿Prueba periódicamente que puede restaurar los backups?', guidance: { why: 'Backups corruptos no sirven en una recuperación real.', steps: ['Realice restauraciones de prueba al menos una vez al año.','Documente tiempos y pasos.'] } },
    { id: '6.3', nistFunction: 'recuperar', title: 'Política de retención', description: 'Definir cuánto tiempo conservar backups.', question: '¿Tiene reglas sobre cuánto tiempo conservar copias de seguridad?', guidance: { why: 'Equilibra costo y necesidad de recuperación.', steps: ['Defina retenciones mínimas según tipo de datos.','Automatice limpieza de copias antiguas.'] } },
    { id: '6.4', nistFunction: 'recuperar', title: 'Procedimiento de recuperación', description: 'Pasos para restaurar operaciones tras un incidente.', question: '¿Existe un procedimiento para restaurar servicios clave después de un incidente?', guidance: { why: 'Acelera el regreso a operación normal.', steps: ['Priorice sistemas a restaurar.','Defina responsables y tiempos objetivo.'] } },

    { id: '7.1', nistFunction: 'proteger', title: 'Defensa antimalware', description: 'Protección básica contra malware en endpoints.', question: '¿Todos los endpoints tienen protección antimalware activa y actualizada?', guidance: { why: 'Mitiga riesgos por software malicioso común.', steps: ['Instale antimalware en todos los equipos.','Configure actualizaciones automáticas.'] } },
    { id: '7.2', nistFunction: 'proteger', title: 'Filtrado de email básico', description: 'Protecciones para reducir phishing y spam.', question: '¿Su correo empresarial tiene algún filtro o protección anti-phishing?', guidance: { why: 'Reduce riesgo de suplantación y malware por email.', steps: ['Active filtros básicos del proveedor.','Forme a empleados para identificar phishing.'] } },
    { id: '7.3', nistFunction: 'proteger', title: 'Parches automáticos', description: 'Actualizar sistemas operativos y apps críticas.', question: '¿Tiene configuradas actualizaciones automáticas para sistemas críticos?', guidance: { why: 'Los parches cierran vulnerabilidades conocidas.', steps: ['Active actualizaciones automáticas cuando sea seguro.','Monitoree reinicios pendientes tras parches.'] } },
    { id: '7.4', nistFunction: 'proteger', title: 'Gestión de dispositivos móviles', description: 'Controles básicos para móviles corporativos.', question: '¿Hay reglas mínimas para dispositivos móviles que acceden a datos corporativos?', guidance: { why: 'Los móviles son vectores comunes de pérdida de datos.', steps: ['Exija bloqueo y cifrado en móviles.','Considere MDM o control básico de acceso.'] } },

    { id: '8.1', nistFunction: 'detectar', title: 'Registro centralizado simple', description: 'Centralizar logs esenciales en un lugar.', question: '¿Guarda logs esenciales en un lugar centralizado o accesible?', guidance: { why: 'Facilita revisión y análisis ante incidentes.', steps: ['Envie logs de sistemas críticos a una ubicación central.','Asegure acceso y retención mínima.'] } },
    { id: '8.2', nistFunction: 'detectar', title: 'Alertas por actividad anómala', description: 'Notificaciones por comportamiento sospechoso.', question: '¿Recibe alertas cuando hay actividad de acceso inusual?', guidance: { why: 'Detectar patrones tempranos ayuda a mitigar ataques.', steps: ['Configure alertas para múltiples intentos de acceso.','Defina responsables que revisen dichas alertas.'] } },
    { id: '8.3', nistFunction: 'detectar', title: 'Retención mínima de registros', description: 'Período mínimo para conservar logs críticos.', question: '¿Conserva registros suficientes para investigar incidentes simples?', guidance: { why: 'Ayuda a reconstruir eventos y responsabilidades.', steps: ['Defina retención mínima (ej. 30 días).','Asegure almacenamiento y backups de logs importantes.'] } },
    { id: '8.4', nistFunction: 'detectar', title: 'Revisión periódica de cuentas', description: 'Revisar cuentas y accesos de forma regular.', question: '¿Revisa periódicamente cuentas con acceso privilegiado?', guidance: { why: 'Cuentas olvidadas pueden ser explotadas por atacantes.', steps: ['Revise sobras de cuentas cada 3 meses.','Desactive accesos obsoletos.'] } },

    { id: '9.1', nistFunction: 'proteger', title: 'Segmentación básica de red', description: 'Separar redes de invitados y dispositivos IoT.', question: '¿Dispone de segmentación básica (Wi‑Fi invitados, redes separadas)?', guidance: { why: 'Limita movimiento lateral de atacantes.', steps: ['Implemente red de invitados para visitas.','Separe IoT y cámaras del core de negocio.'] } },
    { id: '9.2', nistFunction: 'proteger', title: 'Protección de acceso remoto', description: 'Controles para acceso remoto a sistemas críticos.', question: '¿Controla el acceso remoto a sistemas críticos (VPN, MFA)?', guidance: { why: 'Accesos remotos son puntos de alto riesgo.', steps: ['Use VPN o soluciones seguras.','Active MFA para accesos remotos.'] } },
    { id: '9.3', nistFunction: 'proteger', title: 'Firewalls y controles perimetrales', description: 'Uso de firewall o reglas en el router.', question: '¿Su red tiene reglas básicas de firewall para bloquear servicios innecesarios?', guidance: { why: 'Reduce exposición de servicios a Internet.', steps: ['Cierre puertos innecesarios.','Revise reglas del router periódicamente.'] } },

    { id: '10.1', nistFunction: 'proteger', title: 'Protección de endpoints', description: 'Asegurar endpoints con herramientas y configuraciones.', question: '¿Los endpoints críticos tienen configuraciones estándar de seguridad?', guidance: { why: 'Endpoints mal configurados son vectores fáciles para atacantes.', steps: ['Aplique configuración mínima estándar a todos los endpoints.','Habilite firewall local y antimalware.'] } },
    { id: '10.2', nistFunction: 'proteger', title: 'Control de puertos y servicios', description: 'Desactivar servicios no utilizados en servidores y PC.', question: '¿Desactiva servicios y puertos no utilizados en equipos y servidores?', guidance: { why: 'Servicios innecesarios aumentan la superficie de ataque.', steps: ['Audite servicios activos en servidores.','Desactive servicios innecesarios.'] } },
    { id: '10.3', nistFunction: 'proteger', title: 'Protección de cuentas privilegiadas', description: 'Control y monitoreo de cuentas con privilegios.', question: '¿Monitorea y controla el uso de cuentas privilegiadas?', guidance: { why: 'Abusos de cuentas privilegiadas provocan mayor impacto.', steps: ['Limite uso de cuentas administrativas.','Use cuentas separadas para tareas administrativas.'] } },

    { id: '11.1', nistFunction: 'recuperar', title: 'Backups automáticos', description: 'Implementar copias automáticas de datos críticos.', question: '¿Los datos críticos se respaldan automáticamente?', guidance: { why: 'Automatizar reduce errores humanos y pérdida de datos.', steps: ['Configure backups automáticos con verificación.','Mantenga al menos una copia fuera del sitio.'] } },
    { id: '11.2', nistFunction: 'recuperar', title: 'Restauraciones periódicas', description: 'Probar restauraciones para validar integridad.', question: '¿Hace pruebas de restauración de backups con alguna frecuencia?', guidance: { why: 'Verificar restauraciones confirma que los backups funcionan.', steps: ['Programe al menos una prueba anual.','Documente y corrija problemas detectados.'] } },
    { id: '11.3', nistFunction: 'recuperar', title: 'Versionado y almacenamiento externo', description: 'Mantener versiones y copia externa de backups.', question: '¿Tiene versiones de backups y al menos una copia externa segura?', guidance: { why: 'Versionado ayuda ante encriptación por ransomware.', steps: ['Mantenga múltiples versiones de backups.','Asegure copia en ubicación separada.'] } },
    { id: '11.4', nistFunction: 'recuperar', title: 'Protección de backups', description: 'Asegurar backups contra acceso no autorizado.', question: '¿Los backups están protegidos (acceso, cifrado)?', guidance: { why: 'Backups sin protección pueden ser exfiltrados o manipulados.', steps: ['Cifre backups con claves gestionadas.','Restrinja acceso a backups a personal autorizado.'] } },

    { id: '12.1', nistFunction: 'gobernar', title: 'Evaluación de riesgos simplificada', description: 'Lista corta de riesgos y prioridades.', question: '¿Ha identificado los riesgos principales para su negocio en términos simples?', guidance: { why: 'Focalizar esfuerzos donde más importa.', steps: ['Liste 5 riesgos principales.','Asigne prioridad y acciones para cada uno.'] } },
    { id: '12.2', nistFunction: 'proteger', title: 'Segmentación de datos', description: 'Separar datos sensibles de datos generales.', question: '¿Separa físicamente o lógicamente datos sensibles del resto?', guidance: { why: 'Reduce acceso innecesario a información crítica.', steps: ['Identifique datos sensibles.','Implemente controles de acceso por grupo.'] } },

    { id: '13.1', nistFunction: 'gobernar', title: 'Formación básica en seguridad', description: 'Capacitación mínima para empleados.', question: '¿Ofrece formación básica en ciberseguridad a empleados?', guidance: { why: 'El factor humano es clave en la mayoría de incidentes.', steps: ['Realice una sesión anual mínima.','Envie recordatorios sobre phishing y contraseñas.'] } },
    { id: '13.2', nistFunction: 'gobernar', title: 'Simulacros simples', description: 'Ejercicios básicos para practicar respuesta.', question: '¿Realiza ejercicios o simulacros básicos (p.ej., phishing simulado)?', guidance: { why: 'Practicar mejora la reacción ante incidentes reales.', steps: ['Ejecute pruebas controladas de phishing.','Revise y comparta resultados y lecciones.'] } },

    { id: '14.1', nistFunction: 'gobernar', title: 'Política de uso aceptable', description: 'Reglas de uso de recursos de TI por empleados.', question: '¿Dispone de una política de uso aceptable (internet, correo)?', guidance: { why: 'Clarifica comportamiento esperado y límites de uso.', steps: ['Cree una política corta y clara.','Entregue y haga firmar a empleados cuando sea posible.'] } },
    { id: '14.2', nistFunction: 'gobernar', title: 'Protección de la privacidad mínima', description: 'Medidas básicas para datos personales.', question: '¿Aplica controles básicos sobre datos personales según su jurisdicción?', guidance: { why: 'Cumplir con obligaciones legales y reducir riesgo reputacional.', steps: ['Identifique datos personales manejados.','Aplique controles de acceso y retención mínimos.'] } },

    { id: '15.1', nistFunction: 'responder', title: 'Evaluación post-incidente', description: 'Revisión y aprendizaje tras incidentes.', question: '¿Revisa y aprende de incidentes pasados?', guidance: { why: 'La mejora continua reduce recurrencia.', steps: ['Documente lecciones aprendidas.','Ajuste controles según hallazgos.'] } },
    { id: '15.2', nistFunction: 'responder', title: 'Escalado y soporte externo', description: 'Plan para involucrar soporte externo cuando haga falta.', question: '¿Sabe cuándo y cómo escalar a soporte externo (forense/proveedores)?', guidance: { why: 'Saber escalar evita demoras costosas.', steps: ['Tenga contactos de proveedores (forsense, legal).','Defina criterios de escalado.'] } },

    { id: '16.1', nistFunction: 'proteger', title: 'Seguridad en servicios en la nube', description: 'Controles básicos para servicios en la nube y alojamientos.', question: '¿Aplica controles básicos en servicios en la nube (MFA, roles, backups)?', guidance: { why: 'Servicios en la nube requieren configuración segura por defecto.', steps: ['Active MFA en cuentas administrativas.','Revise permisos y roles de servicios en la nube.'] } },
    { id: '16.2', nistFunction: 'proteger', title: 'Gestión de secretos', description: 'Evitar almacenar credenciales en texto plano.', question: '¿Evita guardar credenciales en archivos de texto o repositorios públicos?', guidance: { why: 'Credenciales expuestas son vectores directos de ataque.', steps: ['Use gestores de secretos o variables de entorno.','No comparta credenciales por email.'] } }
  ]
};

// Expose in global scope (already global by const). If module system needed, adjust accordingly.
